import 'package:amwal_ecr/amwal_ecr.dart';
import 'package:amwal_ecr/amwal_ecr_platform_interface.dart';
import 'package:flutter_test/flutter_test.dart';

import 'platform/fake_host.dart';

/// The three things the 1.0.4 protocol added, from the Dart side.
///
/// * a reference the till chooses, carried on every request and reported on
///   every outcome;
/// * a shared secret, which signs what is sent and checks what comes back;
/// * a follow-up inquiry when an answer never arrives, so an unknown outcome
///   becomes a known one instead of a retry.
///
/// The signing itself happens in the native SDK — the wire format lives there —
/// so what is asserted here is that the setting reaches the host, and that what
/// the host reports about it is read correctly.
void main() {
  const String key = '881dc200c9833da726e9376c2e32cff7';

  late FakeEcrHost host;

  setUp(() => host = FakeEcrHost());
  tearDown(() => host.dispose());

  EcrTerminal terminalWith(EcrConfig config) => EcrTerminal(
        host: '192.168.1.50',
        serialNumber: 'P653200085189',
        config: config,
      );

  group('the shared secret', () {
    test('is refused at construction when it is not usable', () {
      // On the shop floor a bad key is a decline the cashier cannot explain, so
      // it is caught here instead — before a single transaction is sent.
      expect(() => EcrConfig(secureHashKey: 'nothex'), throwsA(isA<EcrArgumentError>()));
      expect(() => EcrConfig(secureHashKey: 'abc'), throwsA(isA<EcrArgumentError>()));
      expect(() => EcrConfig(secureHashKey: 'aabb'), throwsA(isA<EcrArgumentError>()));
    });

    test('an empty key is allowed and means unsigned', () {
      expect(EcrConfig().signsMessages, isFalse);
      expect(EcrConfig(secureHashKey: '').signsMessages, isFalse);
      expect(EcrConfig(secureHashKey: key).signsMessages, isTrue);
    });

    test('is never printed, because a toString ends up in logs', () {
      expect(EcrConfig(secureHashKey: key).toString(), isNot(contains(key)));
      expect(EcrConfig(secureHashKey: key).toString(), contains('signed: true'));
    });

    test('reaches the host, which is where the signing happens', () async {
      host.answer(EcrMethods.sale, approvedPayload());

      await terminalWith(EcrConfig(secureHashKey: key))
          .sale(EcrAmount.parse('1.234'));

      final Map<Object?, Object?> config =
          host.argumentsOf(EcrMethods.sale)[EcrArgs.config]!
              as Map<Object?, Object?>;
      expect(config[EcrConfigKeys.secureHashKey], key);
      expect(config[EcrConfigKeys.autoInquireOnFailure], isTrue);
    });

    test('auto-inquire can be turned off, and says so on the wire', () async {
      host.answer(EcrMethods.sale, approvedPayload());

      await terminalWith(EcrConfig(autoInquireOnFailure: false))
          .sale(EcrAmount.parse('1.234'));

      final Map<Object?, Object?> config =
          host.argumentsOf(EcrMethods.sale)[EcrArgs.config]!
              as Map<Object?, Object?>;
      expect(config[EcrConfigKeys.autoInquireOnFailure], isFalse);
    });

    test('an answer that cannot be shown to be the terminal is unknown, not a '
        'decline', () async {
      // The one reading that must never happen: a till that books this as a
      // refusal will retry, and the cardholder pays twice.
      host.answer(
        EcrMethods.sale,
        failedPayload(
          kind: EcrFailureKinds.unauthenticated,
          message: "The answer was not signed with this terminal's key.",
        ),
      );

      final EcrResult result =
          await terminalWith(EcrConfig(secureHashKey: key))
              .sale(EcrAmount.parse('1.234'));

      expect(result, isA<EcrFailed>());
      expect((result as EcrFailed).failure, isA<EcrUnauthenticated>());
      expect(result.outcomeIsUnknown, isTrue);
      expect(result.nextStep, EcrNextStep.inquireByMerchantReference);
    });
  });

  group("the till's own reference", () {
    test('is sent as given, and comes back on the outcome', () async {
      host.answer(
        EcrMethods.sale,
        approvedPayload(merchantReferenceId: 'ORDER-4471'),
      );

      final EcrResult result = await terminalWith(EcrConfig())
          .sale(EcrAmount.parse('1.234'), merchantReferenceId: 'ORDER-4471');

      expect(
        host.argumentsOf(EcrMethods.sale)[EcrArgs.merchantReferenceId],
        'ORDER-4471',
      );
      expect(result.merchantReferenceId, 'ORDER-4471');
    });

    test('is empty when none is given, so the host generates one', () async {
      host.answer(EcrMethods.sale, approvedPayload());

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      expect(host.argumentsOf(EcrMethods.sale)[EcrArgs.merchantReferenceId], '');
      // Generated by the host and reported back, so a till that numbers nothing
      // still has a handle to inquire by.
      expect(result.merchantReferenceId, 'A1B2C3D4E5F6');
    });

    test('one the wire format cannot carry is refused before anything is sent',
        () async {
      final EcrTerminal terminal = terminalWith(EcrConfig());

      // '&' and '=' are the separators a signed message is built from: a
      // reference carrying one could make two different messages hash alike.
      for (final String bad in <String>[
        'order&1',
        'order=1',
        'order 1',
        'x' * 33,
      ]) {
        expect(
          () => terminal.sale(EcrAmount.parse('1.000'), merchantReferenceId: bad),
          throwsA(isA<EcrArgumentError>()),
          reason: bad,
        );
      }
      expect(host.calls, isEmpty);
    });

    test('travels on every operation, not just a sale', () async {
      host
        ..answer(EcrMethods.voidTransaction, approvedPayload())
        ..answer(EcrMethods.refund, approvedPayload())
        ..answer(EcrMethods.receipt, <String, Object?>{
          EcrResultKeys.outcome: EcrOutcomes.ready,
          EcrResultKeys.merchantReferenceId: 'R-1',
          EcrResultKeys.url: 'https://receipts.amwal-pay.com/1',
          EcrResultKeys.raw: '{}',
        });

      final EcrTerminal terminal = terminalWith(EcrConfig());
      await terminal.voidTransaction('215', merchantReferenceId: 'VOID-1');
      await terminal.refund(
        EcrAmount.parse('0.216'),
        receiptNumber: '208',
        transactionDate: '20260809',
        merchantReferenceId: 'REFUND-1',
      );
      await terminal.receipt(
        receiptNumber: '208',
        transactionDate: '20260809',
        merchantReferenceId: 'RECEIPT-1',
      );

      expect(
        host.argumentValues(EcrArgs.merchantReferenceId),
        <String>['VOID-1', 'REFUND-1', 'RECEIPT-1'],
      );
    });
  });

  group('looking a transaction up by its reference', () {
    Map<String, Object?> foundPayload({String status = 'Approved'}) =>
        <String, Object?>{
          EcrResultKeys.outcome: EcrOutcomes.found,
          EcrResultKeys.merchantReferenceId: 'LOOKUP-1',
          EcrResultKeys.transaction: <String, Object?>{
            EcrTransactionKeys.transactionId: '4471',
            EcrTransactionKeys.stan: '000215',
            EcrTransactionKeys.type: 'Sale',
            EcrTransactionKeys.status: status,
            EcrTransactionKeys.amount: '1.234',
          },
          EcrResultKeys.raw: '{}',
        };

    test('sends the original reference, not this call\'s own', () async {
      host.answer(EcrMethods.inquireByReference, foundPayload());

      await terminalWith(EcrConfig()).inquireByReference(
        'ORDER-4471',
        merchantReferenceId: 'LOOKUP-1',
      );

      final Map<Object?, Object?> args =
          host.argumentsOf(EcrMethods.inquireByReference);
      expect(args[EcrArgs.originalMerchantReference], 'ORDER-4471');
      expect(args[EcrArgs.merchantReferenceId], 'LOOKUP-1');
      // It goes to its own method: the receipt-number lookup is a different
      // question and takes a different field.
      expect(host.countOf(EcrMethods.inquire), 0);
    });

    test('needs the reference it is looking up', () {
      expect(
        () => terminalWith(EcrConfig()).inquireByReference('  '),
        throwsA(isA<EcrArgumentError>()),
      );
      expect(host.calls, isEmpty);
    });

    test('takes no date, because a reference is not scoped to a day', () async {
      host.answer(EcrMethods.inquireByReference, foundPayload());

      await terminalWith(EcrConfig()).inquireByReference('ORDER-4471');

      expect(
        host.argumentsOf(EcrMethods.inquireByReference)[EcrArgs.transactionDate],
        '',
      );
    });

    test('finding the transaction says what became of it', () async {
      host.answer(EcrMethods.inquireByReference, foundPayload());

      final EcrInquiry inquiry =
          await terminalWith(EcrConfig()).inquireByReference('ORDER-4471');

      expect(inquiry, isA<EcrInquiryFound>());
      expect((inquiry as EcrInquiryFound).transaction.status, 'Approved');
      expect(inquiry.merchantReferenceId, 'LOOKUP-1');
    });
  });

  group('an answer that never arrived, and the follow-up', () {
    Map<String, Object?> recoveredPayload(String status) => <String, Object?>{
          ...failedPayload(merchantReferenceId: 'ORDER-4471'),
          EcrResultKeys.recovered: <String, Object?>{
            EcrResultKeys.outcome: EcrOutcomes.found,
            EcrResultKeys.merchantReferenceId: 'ORDER-4471',
            EcrResultKeys.transaction: <String, Object?>{
              EcrTransactionKeys.transactionId: '4471',
              EcrTransactionKeys.stan: '000215',
              EcrTransactionKeys.status: status,
              EcrTransactionKeys.amount: '1.234',
            },
            EcrResultKeys.raw: '{}',
          },
        };

    test('a failure the host followed up carries what it found', () async {
      host.answer(EcrMethods.sale, recoveredPayload('Approved'));

      final EcrResult result = await terminalWith(EcrConfig())
          .sale(EcrAmount.parse('1.234'), merchantReferenceId: 'ORDER-4471');

      final EcrFailed failed = result as EcrFailed;
      expect(failed.failure, isA<EcrTimeout>());
      expect(failed.settled, isTrue);
      expect(failed.recoveredTransaction?.status, 'Approved');
      // The exchange still failed — that is what happened — but the money is no
      // longer in question, so the till books it instead of reconciling it.
      expect(failed.outcomeIsUnknown, isFalse);
    });

    test('a follow-up that found nothing leaves the outcome unknown', () async {
      host.answer(EcrMethods.sale, <String, Object?>{
        ...failedPayload(),
        EcrResultKeys.recovered: <String, Object?>{
          EcrResultKeys.outcome: EcrOutcomes.notFound,
          EcrResultKeys.merchantReferenceId: 'ORDER-4471',
          EcrResultKeys.responseMessage: 'No such transaction',
          EcrResultKeys.raw: '{}',
        },
      });

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      final EcrFailed failed = result as EcrFailed;
      expect(failed.recovered, isA<EcrInquiryNotFound>());
      expect(failed.settled, isFalse);
      // "Not found" is the terminal's answer about its own records, and those
      // are written when a transaction completes — not before. It is evidence,
      // not proof, so the outcome stays unknown.
      expect(failed.outcomeIsUnknown, isTrue);
    });

    test('no follow-up at all is absence, not a failed lookup', () async {
      host.answer(EcrMethods.sale, failedPayload());

      final EcrResult result =
          await terminalWith(EcrConfig(autoInquireOnFailure: false))
              .sale(EcrAmount.parse('1.234'));

      final EcrFailed failed = result as EcrFailed;
      expect(failed.recovered, isNull);
      expect(failed.settled, isFalse);
      expect(failed.outcomeIsUnknown, isTrue);
    });

    test('every failed result asks to be inquired about, never retried',
        () async {
      host.answer(EcrMethods.sale, failedPayload());

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      expect(result.nextStep, EcrNextStep.inquireByMerchantReference);
      expect(result.nextStep.needsInquiry, isTrue);
      // Nothing was sent twice getting here.
      expect(host.countOf(EcrMethods.sale), 1);
    });
  });

  group('a decline the terminal is not sure about', () {
    test('is read as unknown when it asks for an inquiry', () async {
      // A decline normally settles the matter. This one does not, and the
      // terminal is the only side that can say so.
      host.answer(EcrMethods.sale, <String, Object?>{
        ...declinedPayload(responseCode: '05', reason: 'Do not honour'),
        EcrResultKeys.nextStep: EcrNextSteps.inquireByMerchantReference,
      });

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      expect(result, isA<EcrDeclined>());
      expect(result.nextStep, EcrNextStep.inquireByMerchantReference);
      expect(result.outcomeIsUnknown, isTrue);
    });

    test('an ordinary decline still settles the matter', () async {
      host.answer(EcrMethods.sale, declinedPayload());

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      expect(result.nextStep, EcrNextStep.none);
      expect(result.outcomeIsUnknown, isFalse);
    });

    test('a step this version has not heard of is not acted on', () async {
      host.answer(EcrMethods.sale, <String, Object?>{
        ...declinedPayload(),
        EcrResultKeys.nextStep: 'PHONE_THE_ACQUIRER',
      });

      final EcrResult result =
          await terminalWith(EcrConfig()).sale(EcrAmount.parse('1.234'));

      expect(result.nextStep, EcrNextStep.none);
    });
  });
}
