// swift-tools-version: 5.9
import PackageDescription

// GENERATED by tool/sync_ios_ecr_sdk.sh — do not hand-edit dependency mode.
// Source of truth: ios/ecr_sdk.properties (+ example/ios/ecr_sdk.properties).
// CocoaPods face: ../amwal_ecr.podspec (same AmwalECR version range).
let package = Package(
    name: "amwal_ecr",
    platforms: [
        .iOS("17.0"),
    ],
    products: [
        .library(name: "amwal-ecr", targets: ["amwal_ecr"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/amwal-pay/AmwalECR-iOS-SPM.git",
            .upToNextMinor(from: "0.2.3")
        ),
    ],
    targets: [
        .target(
            name: "amwal_ecr",
            dependencies: [
                .product(name: "AmwalECR", package: "AmwalECR-iOS-SPM"),
            ]
        ),
    ]
)
