// swift-tools-version: 5.9
import PackageDescription

// GENERATED by tool/sync_ios_ecr_sdk.sh — do not hand-edit dependency mode.
// Source of truth: ios/ecr_sdk.properties (+ example/ios/ecr_sdk.properties).
// CocoaPods face: ../amwal_ecr.podspec (same AmwalECR version range).
let package = Package(
    name: "amwal_ecr",
    platforms: [
        .iOS("12.0"),
    ],
    products: [
        .library(name: "amwal-ecr", targets: ["amwal_ecr"]),
    ],
    dependencies: [
        // The wire protocol: its own package, used unchanged by native iOS
        // apps. Ranged to the patch line for the reason given in the podspec.
        .package(
            url: "https://github.com/amwal-pay/AmwalECR-iOS-SPM.git",
            .upToNextMinor(from: "0.2.1")
        ),
        // .package(path: "../../../AmwalECR-iOS-SPM"),
    ],
    targets: [
        .target(
            name: "amwal_ecr",
            dependencies: [
                .product(name: "AmwalECR", package: "AmwalECR-iOS-SPM"),
            ]
        ),
    ]
)
