#!/usr/bin/env bash
# Sync the iOS plugin's AmwalECR dependency across:
#   - ios/ecr_sdk.properties          (canonical, like android/gradle.properties)
#   - ios/amwal_ecr.podspec           (CocoaPods face)
#   - ios/amwal_ecr/Package.swift     (SwiftPM face)
#   - example/ios/ecr_sdk.properties  (example overrides)
#   - example/pubspec.yaml            (enable-swift-package-manager)
#
# Modes (ecrSdkDependency):
#   project   — local sibling checkouts (CocoaPods path + SPM path)
#   cocoapods — published CocoaPods trunk; Package.swift stays on GitHub tags
#   spm       — published SwiftPM; example enables Flutter SPM
#
# Usage (from plugin root):
#   ./tool/sync_ios_ecr_sdk.sh
#   ECR_SDK_DEPENDENCY=cocoapods ./tool/sync_ios_ecr_sdk.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
plugin_props="$root/ios/ecr_sdk.properties"
example_props="$root/example/ios/ecr_sdk.properties"
package_swift="$root/ios/amwal_ecr/Package.swift"
podspec="$root/ios/amwal_ecr.podspec"
example_pubspec="$root/example/pubspec.yaml"

load_props() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(echo "$key" | xargs)"
    value="$(echo "$value" | xargs)"
    [[ -n "$key" ]] || continue
    printf -v "PROP_$key" '%s' "$value"
  done < "$file"
}

# Plugin defaults, then example overrides (same as Gradle findProperty from example).
load_props "$plugin_props"
PLUGIN_COCOA_ROOT_FILE="$plugin_props"
PLUGIN_SPM_ROOT_FILE="$plugin_props"
COCOA_ROOT_BASE="$(dirname "$plugin_props")"
SPM_ROOT_BASE="$(dirname "$plugin_props")"

if [[ -f "$example_props" ]]; then
  load_props "$example_props"
  COCOA_ROOT_BASE="$(dirname "$example_props")"
  SPM_ROOT_BASE="$(dirname "$example_props")"
fi

MODE="${ECR_SDK_DEPENDENCY:-${PROP_ecrSdkDependency:-cocoapods}}"
VERSION="${PROP_ecrSdkVersion:-0.2.1}"
COCOA_ROOT_REL="${ECR_SDK_ROOT:-${PROP_ecrSdkCocoaPodsRoot:-../../AmwalECR-iOS-CocoaPods}}"
SPM_ROOT_REL="${PROP_ecrSdkSpmRoot:-../../AmwalECR-iOS-SPM}"

COCOA_ROOT="$(cd "$COCOA_ROOT_BASE" && cd "$COCOA_ROOT_REL" 2>/dev/null && pwd || true)"
SPM_ROOT="$(cd "$SPM_ROOT_BASE" && cd "$SPM_ROOT_REL" 2>/dev/null && pwd || true)"

case "$MODE" in
  project|cocoapods|spm) ;;
  *)
    echo "Unknown ecrSdkDependency='$MODE'. Use: project | cocoapods | spm" >&2
    exit 1
    ;;
esac

# Path from ios/amwal_ecr/Package.swift to the SPM checkout.
spm_package_path_for_manifest() {
  python3 - <<'PY' "$package_swift" "$SPM_ROOT"
import os, sys
manifest_dir = os.path.dirname(os.path.abspath(sys.argv[1]))
sdk = os.path.abspath(sys.argv[2])
print(os.path.relpath(sdk, manifest_dir))
PY
}

write_package_swift() {
  local dependency_block="$1"
  local package_id="$2"
  cat > "$package_swift" <<EOF
// swift-tools-version: 5.9
import PackageDescription

// GENERATED by tool/sync_ios_ecr_sdk.sh — do not hand-edit dependency mode.
// Source of truth: ios/ecr_sdk.properties (+ example/ios/ecr_sdk.properties).
// CocoaPods face: ../amwal_ecr.podspec (same AmwalECR version range).
let package = Package(
    name: "amwal_ecr",
    platforms: [
        .iOS("12.0"),
    ],
    products: [
        .library(name: "amwal-ecr", targets: ["amwal_ecr"]),
    ],
    dependencies: [
${dependency_block}
    ],
    targets: [
        .target(
            name: "amwal_ecr",
            dependencies: [
                .product(name: "AmwalECR", package: "${package_id}"),
            ]
        ),
    ]
)
EOF
}

echo "[amwal_ecr] iOS ecrSdkDependency=$MODE  version=$VERSION"

# --- Package.swift (SwiftPM face) ---
case "$MODE" in
  project)
    if [[ -z "$SPM_ROOT" || ! -d "$SPM_ROOT" ]]; then
      echo "Local AmwalECR-iOS-SPM not found (ecrSdkSpmRoot=$SPM_ROOT_REL)." >&2
      exit 1
    fi
    rel="$(spm_package_path_for_manifest)"
    echo "[amwal_ecr] Package.swift → local path $rel"
    write_package_swift "        .package(path: \"$rel\")," "AmwalECR-iOS-SPM"
    ;;
  cocoapods|spm)
    echo "[amwal_ecr] Package.swift → GitHub AmwalECR-iOS-SPM $VERSION"
    write_package_swift "        .package(
            url: \"https://github.com/amwal-pay/AmwalECR-iOS-SPM.git\",
            .upToNextMinor(from: \"$VERSION\")
        )," "AmwalECR-iOS-SPM"
    ;;
esac

# --- podspec version (CocoaPods face always declares the published range) ---
if [[ "$(uname)" == Darwin ]]; then
  sed -i '' -E "s/s\.dependency 'AmwalECR', '~> [^']+'/s.dependency 'AmwalECR', '~> ${VERSION}'/" "$podspec"
else
  sed -i -E "s/s\.dependency 'AmwalECR', '~> [^']+'/s.dependency 'AmwalECR', '~> ${VERSION}'/" "$podspec"
fi
echo "[amwal_ecr] podspec → AmwalECR ~> $VERSION"

# --- example Flutter SPM toggle ---
# Local example path-dep folder name ≠ package name, so SPM is only for mode=spm
# (integrators / CI). Local live sources use mode=project via CocoaPods.
case "$MODE" in
  spm) spm_flag=true ;;
  *) spm_flag=false ;;
esac

if [[ "$(uname)" == Darwin ]]; then
  sed -i '' -E "s/(enable-swift-package-manager: ).*/\1${spm_flag}/" "$example_pubspec"
else
  sed -i -E "s/(enable-swift-package-manager: ).*/\1${spm_flag}/" "$example_pubspec"
fi
echo "[amwal_ecr] example enable-swift-package-manager=$spm_flag"

if [[ "$MODE" == project ]]; then
  if [[ -z "$COCOA_ROOT" || ! -d "$COCOA_ROOT" ]]; then
    echo "Warning: AmwalECR-iOS-CocoaPods not found at $COCOA_ROOT_REL (needed for example pods)." >&2
  else
    echo "[amwal_ecr] example CocoaPods will use $COCOA_ROOT"
  fi
fi

echo "[amwal_ecr] iOS SDK dependency sync complete."
